language: android
jdk:
    - oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - android-25
    - extra-android-m2repository

script: ./gradlew build connectedCheck

licenses:
  - '.+'


