language: android
jdk:
    - oraclejdk8
android:
  components:
    - tools
    - build-tools-27.0.3
    - platform-tools
    - android-27
    - extra-android-m2repository

script: ./gradlew -Dorg.gradle.jvmargs=-Xmx1536m assembleDebug lintDebug testDebugUnitTest

licenses:
  - '.+'


